name = "kiss-worker"
main = "src/index.js"
compatibility_date = "2023-07-28"
kv_namespaces = [
    { binding = "KV", id = "b29c19826d3e43d0ae00b3cc87f01c62", preview_id = "b29c19826d3e43d0ae00b3cc87f01c62" }
]
